config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  resources :users, only: [:index, :show, :edit, :update, :create]
	get '/users/:id/activate', to: 'users#activate'
  get '/register', to: 'users#new'

  root to: 'welcome#index'
  get '/dashboard', to: 'welcome#show'

  post '/notification' => 'notification#create'

	get '/login'     => 'sessions#new'
	post '/login'    => 'sessions#create'
	delete '/logout' => 'sessions#destroy'


  namespace :api do
    namespace :v1 do
      resources :games, only: [:show, :create] do
        post "/shots", to: "games/shots#create"
        post "/ships", to: "games/ships#create"
      end

      resources :users, only: [:index, :show, :update]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  attr_accessor :messages

  enum current_turn: ["player_1", "player_2"]
  serialize :player_1_board
  serialize :player_2_board

  validates :player_1_board, presence: true
  validates :player_2_board, presence: true
end

app/models/shooter.rb
class Shooter
  def initialize(board:, target:)
    @board     = board
    @target    = target
    @message   = ""
    @health     = 5
  end

  def fire!
    if valid_shot?
      result = space.attack!
      @board.health -= 1
      if @board.health == 0
        result + " Game over."
      else
        result
      end
    else
      raise InvalidAttack.new("Invalid coordinates.")
    end
  end

  def self.fire!(board:, target:)
    new(board: board, target: target).fire!
  end

  private
    attr_reader :board, :target

    def space
      @space ||= board.locate_space(target)
    end

    def valid_shot?
      board.space_names.include?(target)
    end
end

class InvalidAttack < StandardError
  def initialize(msg = "Invalid attack.")
    super(msg)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/api/v1/games/ships_controller.rb
module Api
  module V1
    module Games
      class ShipsController < ApiController
        def create
          game = Game.find(params[:game_id])
          ship = Ship.new(params[:ship_size])
          player = PlayerSelector.new(request.headers["X-API-Key"], game)
          placer = ShipPlacer.new(board: player.assets[:board],
                                  ship: ship,
                                  start_space: params[:start_space],
                                  end_space: params[:end_space]
                                )
          placer.run
          game.save
          render json: game, message: placer.gen_message
        end
      end
    end
  end
end

app/controllers/api/v1/games/shots_controller.rb
module Api
  module V1
    module Games
      class ShotsController < ApiController
        def create
          game = Game.find(params[:game_id])
          api = request.headers["X-API-Key"]
          if api == game.player_1_api_key || api == game.player_2_api_key
            render TurnProcessor.new(game, params[:shot][:target], request.headers["X-API-Key"]).message
          else
            render json: game, status: 401, message: 'Unauthorized'
          end
        end
      end
    end
  end
end

app/controllers/api/v1/games_controller.rb
module Api
  module V1
    class GamesController < ActionController::API
      def show
        game = Game.find_by(id: params[:id])
        render status: 400 unless game
        render json: game if game
      end

      def create
        board_1 = Board.new(4)
        board_2 = Board.new(4)
        game = Game.create(player_1_board: board_1,
                        player_2_board: board_2,
                        player_1_api_key: request.headers["X-API-Key"],
                        player_2_api_key: User.find_by(email: request["opponent_email"]).api_key)
        render json: game if game
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApiController
      def index
        render json: User.all
      end

      def show
        render json: User.find(params[:id])
      end

      def update
        user = User.find(params[:id])
        user.update(email: params[:email])
        render json: user
      end

    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email].downcase)

    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id.to_s
      redirect_to root_path, notice: 'Successfully logged in!'
    else
      flash[:notice] = "Incorrect email or password, try again."
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
require 'securerandom'

  def show
    @response = UserApiInterface.new(:user, params).get_json
    @user = User.new(@response)
  end

  def index
    @response = UserApiInterface.new(:users).get_json
    @users = @response.map do |user_response|
      User.new(user_response)
    end
  end

  def edit
    @user = params[:id]
  end

  def update
    api_interface    = UserApiInterface.new(:user, params)
    raw_user         = api_interface.update_email
    parsed_user      = api_interface.parse_json(raw_user)
    flash[:notice] = "Successfully updated #{parsed_user[:name]}"
    redirect_to users_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      @user.update(api_key: SecureRandom.urlsafe_base64)
      session[:user_id] = @user.id.to_s
    	UserMailer.activate(@user).deliver_now
      redirect_to '/dashboard'
    else
      render :new
      flash[:notice] = "Failed to Create User"
    end
  end

	def activate
		@user = User.find(params[:id])
		if @user.api_key == params[:key]
			@user.update( active: true)
    	flash[:notice] = "Thank you! Your account is now activated."
		else
    	flash[:notice] = "Wrong User Token"
		end
			redirect_to '/dashboard'
	end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def show
    @user = User.find(current_user.id)
    if @user.active == false
      @notice = "This account has not yet been activated. Please check your email."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BattleshipWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: type %>
    <% end %>
    <% if current_user %>
      <%= "Logged in as #{current_user.name}" %> | <%= link_to 'Home', '/'%> | <%= link_to 'Log Out', logout_path, method: :delete %>
    <% else %>
      <%= link_to 'Home', '/'%> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', '/register'%>
    <% end %>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_tag("/users/#{@user}", method: "patch") do %>
  <%= label_tag(:email, "Email") %>
  <%= text_field_tag(:email) %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/users/index.html.erb
<h1> Users </h1>

<% @users.each do |user| %>
  <ul id=<%= "user-#{user.id}" %>>
    <li><%= user.name %></li>
    <li><%= user.email %></li>
    <li><%= link_to 'Edit', edit_user_path(user.id)%></li>
</ul>
  <% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Submit"%>
  </div>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>

app/views/welcome/index.html.erb
<%= link_to 'Register', '/register' %>

app/views/welcome/show.html.erb
dashboard
<%= @notice unless @notice.nil? %>
Status: <%= @user.active %>